language: ruby

rvm:
  - "2.3.0"
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9"

sudo: false

install:
  - bundle install -j4 --path vendor/bundle

script:
  - bundle exec rake spec

cache:
  directories:
    - vendor/bundle
    - spec/api_fixtures

deploy:
  provider: rubygems
  api_key:
    master:
      secure: "S9CaXZnIJa0JxHbASoYRKtHeITtxbmGN47zDQJDSIwN2dF3P2si8bhx4JL+dmhyhZhq/yB8vmVaBbCB2Qd7PZEBL6WyD0H8TJ0o0DbX2i/iHxzvNX1GYLsVH0sem2rf7kfyuxP+IO2wgbJe5itddwrTVsgUtm1IfGRIwnjHdCus="
  gem:
    master: codeforces
  on:
    repo: sh19910711/ruby-codeforces-api-client
    ruby: "2.3.0"

