version: "{build}"

# TODO: not working?
environment:
  matrix:
    - ruby_version: "22-x64"
    - ruby_version: "22"
    - ruby_version: "21-x64"
    - ruby_version: "21"
    - ruby_version: "200-x64"
    - ruby_version: "200"
    - ruby_version: "193"

cache:
  - vendor/bundle

build_script:
  - cmd: gem install bundler
  - cmd: bundle install --path vendor/bundle

test_script:
  - cmd: bundle exec rake spec
